install.packages("rworldmap")
install.packages("ggplot2")
install.packages("reshape2")
install.packages("wordcloud2")
install.packages("plyr")
install.packages("ggridges")
install.packages("gganimate")
install.packages("RColorBrewer")
install.packages(“plotly”, repos=“http://cran.rstudio.com/ 222”, dependencies=TRUE)